# -*- coding: utf-8 -*-
"""Tarea 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlgGfVTCHJlvkrwYWQbmBYoCXa-_FDW6
"""

#Bicho
#Corrija los dos errores en el código para que pueda ejecutarse.

print("Uno, dos, tres...")
print("... cuatro, cinco, seis.")

#Poema
#Añada algunas sentencias printal final del código

w = "La noche está estrellada, y tiritan, azules, los astros, a lo lejos"
x = "Puedo escribir los versos más tristes esta noche."
y = "Escribir, por ejemplo:"
z = "El viento de la noche gira en el cielo y canta."

espacio = " "
print(x)
print(y,espacio,w )
print( z)

#Promedio
#Desarrolle un programa que calcule el promedio de las cuatro prácticas del curso.
#El campus virtual requiere que la nota sea un número entero, por lo que el promedio se debe redondear a tu favor.

primera_practica = 16
segunda_practica = 13
tercera_practica = 19
cuarta_practica = 8
promedio_de_practicas = (primera_practica + segunda_practica + tercera_practica + cuarta_practica)/4

print(promedio_de_practicas)